# Generated by Django 5.0.4 on 2024-04-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=10)),
                ('deal_bas_r', models.FloatField()),
                ('search_date', models.DateTimeField()),
            ],
        ),
    ]
