# Generated by Django 5.0.4 on 2024-04-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_kospi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="oilprice",
            old_name="oil_category",
            new_name="oil_type",
        ),
        migrations.AddField(
            model_name="kospi",
            name="type",
            field=models.CharField(default="KOSPI", max_length=100),
        ),
    ]
