# Generated by Django 5.0.4 on 2024-04-17 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_oil_category_oilprice_oil_type_kospi_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goldprice",
            name="gold_type",
        ),
        migrations.AddField(
            model_name="goldprice",
            name="type",
            field=models.CharField(default="gold", max_length=100),
        ),
    ]
