# Generated by Django 5.0.4 on 2024-04-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_goldprice_gold_type_goldprice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldprice",
            name="type",
            field=models.CharField(default="Gold", max_length=100),
        ),
    ]
