# Generated by Django 5.0.4 on 2024-04-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_goldprice_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WTIOilPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="WTI_Oil", max_length=100)),
                ("date", models.DateField()),
                ("closing_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
