# Generated by Django 5.0.4 on 2024-04-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_wtioilprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasdaqIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Nasdaq', max_length=100)),
                ('date', models.DateField()),
                ('index', models.FloatField()),
            ],
        ),
    ]
