# Generated by Django 5.0.4 on 2024-04-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_nasdaqindex'),
        ('polls', '0006_wtioilprice'),
    ]

    operations = [
    ]
