# Generated by Django 5.0.4 on 2024-04-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_merge_0002_nasdaqindex_0006_wtioilprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasdaqindex',
            name='type',
            field=models.CharField(default='Nasdaq', max_length=100),
        ),
    ]
