# Generated by Django 5.0.4 on 2024-04-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_exchangerate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nasdaqindex',
            old_name='index',
            new_name='index_price',
        ),
    ]
